modLoader="javafml"
loaderVersion="[41,)"
license="${license}"
issueTrackerURL="${issues}"
logoFile="${mod_id}_icon.png"
logoBlur=false
[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
authors="${mod_author}"
description='''
${mod_description}
'''
displayURL="${source}"
[[dependencies.spectrelib]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.spectrelib]]
    modId="minecraft"
    mandatory=true
    versionRange="${forge_mc_version_range}"
    ordering="NONE"
    side="BOTH"
