# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version=0.22.0+26.2
group=com.illusivesoulworks.spectrelib
java_version=25

# Common
minecraft_version=26.2
mod_name=SpectreLib
mod_author=Illusive Soulworks
mod_id=spectrelib
license=LGPL-2.1-only
issues_url=https://github.com/illusivesoulworks/spectrelib/issues
sources_url=https://github.com/illusivesoulworks/spectrelib
mod_description=Cross-platform library for Illusive Soulworks mods.
minecraft_version_range=[26.2,)
minecraft_version_range_alt=~26.2

## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.2-1

# NightConfig
nightconfig_version=3.9.0

# Fabric
fabric_version=0.152.1+26.2
fabric_loader_version=0.19.3
mod_menu_version=20.0.0-beta.4

# Forge
forge_version=65.0.0
forge_version_range=[62,)

# NeoForge
neoforge_version=26.2.0.0-beta
neoforge_version_range=[26.1,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
